#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a ffsync
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Generate random passworid
db_pwd=$(head -c 8 /dev/urandom | sha1sum | cut -d " " -f1)

# Use 'FSyncMS' as database name and user
db_user=ffsync

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting ffsync mysqlpwd -v $db_pwd

# Check depends installation
sudo apt-get install make python-dev python-virtualenv -y

# Check Swap
tmp_swap_file=/tmp/ffsync_swapfile
if [ $(sudo swapon -s | wc -l) = 1 ];
then
	sudo dd if=/dev/zero of=$tmp_swap_file bs=1M count=256
	sudo chmod 600 $tmp_swap_file
	sudo mkswap $tmp_swap_file
	sudo swapon $tmp_swap_file
fi

# Copy files to the right place
final_path=/opt/yunohost/ffsync
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/ffsync /etc/init.d/

# Set permissions to ffsync directory
sudo useradd ffsync -d $final_path
sudo chown ffsync:ffsync -R $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
secret=$(head -c 20 /dev/urandom | sha1sum | cut -d " " -f1)
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/ffsync.conf
sudo cp ../conf/syncserver.ini $final_path/syncserver.ini
sudo sed -i -e "s@ynhbaseurl@$domain$path@g" $final_path/syncserver.ini
sudo sed -i -e "s@changesecret@$secret@g" $final_path/syncserver.ini
sudo sed -i "s/yunouser/$db_user/g" $final_path/syncserver.ini
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/syncserver.ini
sudo sed -i "s/yunobase/$db_user/g" $final_path/syncserver.ini

# Init virtualenv
cd $final_path && sudo make build && sudo ./local/bin/easy_install gunicorn

# Disable swapfile
if [ -f $tmp_swap_file ];
then
        sudo swapoff $tmp_swap_file
        sudo rm -f $tmp_swap_file
fi

# Fix permission
sudo find $final_path/ -type d -exec chmod 2755 {} \;
sudo find $final_path/ -type f -exec chmod g+r,o+r {} \;
sudo usermod -a -G ffsync www-data

#enable services
sudo chmod +x /etc/init.d/ffsync
sudo update-rc.d ffsync defaults
sudo service ffsync start

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost service add firefox-sync -l /var/log/ffsync.log
sudo yunohost app setting ffsync skipped_uris -v "/"
sudo yunohost app ssowatconf
