#!/bin/bash

db_user=wordpress
db_name=wordpress
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting ffsync domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/ffsync
sudo rm -f /etc/nginx/conf.d/$domain.d/ffsync.conf
