#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting ffsync domain)
path=$(sudo yunohost app setting ffsync path)
db_pwd=$(sudo yunohost app setting  ffsync mysqlpwd)
db_user=ffsync
final_path=/opt/yunohost/ffsync

# Get secret variable
secret=$(sudo yunohost app setting ffsync secret)
# Get from conf file if not defined
if [[ -z $secret ]]
then
	secret=$(sudo grep "secret =" $final_path/syncserver.ini | cut -d" " -f3)
	sudo yunohost app setting $app secret -v $secret
fi

# Check Swap
if [ $(sudo swapon -s | wc -l) = 1 ];
then
	# It is NOT possible to setup a swap file on a tmpfs filesystem
	mount | grep /tmp | grep tmpfs > /dev/null 2>&1
	if [ $? = 1 ];
	then
		tmp_swap_file=/tmp/ffsync_swapfile
	else
		tmp_swap_file=/var/cache/ffsync_swapfile
	fi
	sudo dd if=/dev/zero of=$tmp_swap_file bs=1M count=256
	sudo chmod 600 $tmp_swap_file
	sudo mkswap $tmp_swap_file
	sudo swapon $tmp_swap_file
fi

# Copy files to the right place
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path
sudo cp ../conf/ffsync /etc/init.d/
sudo cp ../conf/ffsync.logrotate /etc/logrotate.d/ffsync

# Set permissions to ffsync directory
sudo useradd ffsync -d $final_path
sudo chown ffsync:ffsync -R $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/ffsync.conf
sudo cp ../conf/syncserver.ini $final_path/syncserver.ini
sudo sed -i -e "s@ynhbaseurl@$domain$path@g" $final_path/syncserver.ini
sudo sed -i -e "s@changesecret@$secret@g" $final_path/syncserver.ini
sudo sed -i "s/yunouser/$db_user/g" $final_path/syncserver.ini
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/syncserver.ini
sudo sed -i "s/yunobase/$db_user/g" $final_path/syncserver.ini

# stop service before upgrade
sudo service ffsync stop

# Init virtualenv
cd $final_path && sudo make build && sudo ./local/bin/easy_install gunicorn

# Disable swapfile
if [ -z ${tmp_swap_file+x} ];
then
        sudo swapoff $tmp_swap_file
        sudo rm -f $tmp_swap_file
fi

# Fix permission
sudo find $final_path/ -type d -exec chmod 2755 {} \;
sudo find $final_path/ -type f -exec chmod g+r,o+r {} \;
sudo usermod -a -G ffsync www-data

#enable services
sudo chmod +x /etc/init.d/ffsync
sudo update-rc.d ffsync defaults
sudo service ffsync restart
sudo service ffsync restart
sudo service ffsync restart

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting ffsync skipped_uris -v "/"
sudo yunohost app ssowatconf
